project:
  type: website
  output-dir: docs

website:
  title: "PECR Knowledge Hub"
  navbar:
    title: false
    logo: "./recursos/imagenes/generales/logo.svg"
    left:
      - href: index.qmd
        text: Principal
      - text: Acerca de mi
        href: about.qmd

navbar:
  right:

format:
  html:
    mermaid:
      theme: dark
    theme: cosmo
    jupyter: python_jupyter # Se debe tener en cuenta para poder ejecutar ipynb files. En linux se debe ejecutar esto sudo python -m ipykernel install --name python_jupyter
    text-align: justify
    wrap: preserve
    css: "./recursos/estilos/styles_site.css"
    toc: false



