---
title: "Taller 1 - Sistemas y Señales Biomédicos"
author: "Jenny Carolina Castiblanco Sánchez, Pablo Eduardo Caicedo Rodríguez"
date: today
format: html
editor: visual
---


Taller 1

Profesores

Jenny Carolina Castiblanco Sánchez

Pablo Eduardo Caicedo Rodríguez

Descripción

A través de este taller se reforzarán los conocimientos en: señales, transformaciones de la variable independiente, clasificación de señales, ADC y DAC.

Procedimiento

Explique detalladamente el procedimiento para cada uno de los puntos enunciados a continuación.

Considere la señal

Dibuje:

Determine si las siguientes señales son periódicas y encuentre su periodo

Para las siguientes señales encuentre, la potencia instantánea, la energía y la potencia promedio. Indique si la señal se considera de energía o de potencia.

Demuestre que si  y  son señales impares, entonces:

, es una señal par

es una señal impar.

Siendo  y , grafique en Python  y . ¿se cumple lo indicado en el numeral a y b?

Encuentre la expresión analítica de las señales mostradas a continuación utilizando funciones  y  (escalón unitario y rampa).

Para una señal análoga   encontrar

Indique si la señal  es una señal periódica, en caso afirmativo, indique el periodo de la señal.

Frecuencia de muestro que cumpla con el teorema de Nyquist.

Encontrar  con la frecuencia de muestreo encontrada en el punto anterior.

Indique si la señal   es una señal periódica, en caso afirmativo, indique el periodo de la señal.

Considere el sistema de procesamiento de señales mostrado en la figura:

Recuerde que . Si la entrada es , encontrar:

La salida  si . ¿Con esta frecuencia se puede reconstruir la señal  en  si ? Justifique su respuesta.

La salida  si la frecuencia de muestreo del ADC es 8 veces la frecuencia de Nyquist. ¿La señal es periódica en tiempo discreto? Justifique su respuesta.

Para la señal del punto b, encontrar la señal cuantizada de un ciclo de la señal si el tamaño del registro es de 4bits y el rango de valores que maneja a la entrada es de 0 a 5.
