---
title: "Taller3: Análisis y diseños de filtros"
author: 
    - Jenny Carolina Castiblanco Sánchez
    - Pablo Eduardo Caicedo Rodríguez"
date: today
format: html
editor: visual
---

# Profesores

Jenny Carolina Castiblanco Sánchez

Pablo Eduardo Caicedo Rodríguez

# Descripción

A través de este taller se reforzarán los conocimientos en:

-   Transformada Z
-   Diseño, análisis e implementación de filtros digitales FIR e IIR

# Procedimiento

Explique detalladamente el procedimiento para cada uno de los puntos enunciados a continuación.

1.  **Transformada Z y Región de Convergencia**\
    Determine la transformada Z y dibuje la ROC de las siguientes señales:

    -   $x\left[n\right] = =\begin{cases}\displaystyle \left(\frac{1}{3}\right)^{n}, & n \ge 0,\\[6pt]\displaystyle \left(\frac{1}{2}\right)^{-n}, & n < 0.\end{cases}$
    -   $x\left[n\right]=\begin{cases}\displaystyle \left(\frac{1}{3}\right)^{n}, & n \ge 5,\\[6pt]0, & n < 5.\end{cases}$

2.  **Respuesta del Sistema**

    Determine la respuesta del sistema

    $$
    y\left[n\right] \;=\; \frac{5}{6}\,y\left[n-1\right]\;-\;\frac{1}{6}\,y\left[n-2\right]\;+\;x\left[n\right]
    $$

    A la señal de entrada

    $$
    x\left[n\right] \;=\; \delta\left[n\right]\;-\;\frac{1}{3}\,\delta\left[n-1\right]
    $$

3.  **Respuesta del Sistema**\
    Una señal de entrada ( $x[n] = 3^{n}u[-n]$ ) es aplicada a un sistema LTI discreto con respuesta al impulso ( $h[n] = \left(0.5\right)^{n}u[n]$ ).

    -   Determine la función de transferencia del sistema.
    -   ¿El sistema es estable?
    -   Encuentre la señal de salida del sistema.

4.  **Análisis de Filtro**\
    Considere el filtro

    $$y\left[n\right] \;=\; b\,x\left[n\right]\;-\;0.65\,y\left[n-1\right]$$

    -   Determine (b) de modo que $\lvert H\left[0\right] \lvert \, = \, 0$\
    -   Dibuje en el plano (z) el diagrama de polos y ceros. ¿El sistema es estable?\
    -   Grafique el diagrama de bloques.\
    -   ¿Qué tipo de filtro es?

5.  **Diseño de Filtro Analógico Muestreado**\
    La salida de un sistema LTI está determinada por la ecuación del sistema.

    $$
    y\left[n\right] \;=\; x\left[n\right]\;-\;a\,y\left[n-1\right]
    $$\
    Teniendo en cuenta la función de transferencia, se desea diseñar un filtro con frecuencia de corte de 60 Hz para una señal analógica muestreada a 5 kHz.

    -   ¿Qué valor debe tener la variable (a)?\

    -   ¿Qué tipo de filtro se obtiene?

<!-- -->

6.  **Diseñar y simular filtros digitales para señales empleando PYTHON.**
    -   Diseñar, simular y analizar un filtro pasbajos FIR por el método de ventaneo, con frecuencia de corte de 55Hz a los 6dB, atenuación mínima en 60Hz de 20 dB y atenuación mayor de 40 dB por encima de 80Hz.

        -   Determinar el mínimo orden del filtro requerido para las siguientes ventanas: Rectangular, triangular, Hann, Hamming, Blackman, Kayser.

        -   De los filtros analizados, seleccione el de menor orden que cumpla con las características de diseño.

    -   Diseñar y simular filtros digitales IIR para señales de voz empleando Matlab, analizando las diferentes opciones: Butterworth, Chebyshev, Elíptico.

        -   Diseñar, simular y analizar un filtro pasabajos IIR por el método de transformación de filtros analógicos empleando la transformación bilineal, con las siguientes características: Frecuencia de muestreo, 8 kHz; frecuencia de corte de 3.4 kHz; rizado en la banda de paso, 1 dB; frecuencia de rechazo, 3.8 kHz; atenuación en la banda de rechazo, 30 dB; orden del filtro, mínimo.

        -   Diseñar, simular y analizar un filtro pasaltos IIR por el método de transformación de filtros analógicos empleando la transformación bilineal, con las siguientes características: Frecuencia de muestreo, 8 kHz; frecuencia de corte de 300 Hz; rizado en la banda de paso, 1 dB; frecuencia de rechazo, 60 Hz; atenuación en la banda de rechazo, 30 dB; orden del filtro, mínimo.