---
title: Procesamiento de Señales e Imágenes Médicas
coursecode: PSIM-80
date: 2024-10-21
year: 2024
period: 2
timeallowed: Una Hora.
openorclosed: Apuntes con caligrafía propia.
permitted: NO se permite comunciación con compañeros ni préstamo de elementos.
instructions: |
   Responda cada pregunta según las instrucciones de la sección
   
   El examen consta de un total de **50** puntos.
   
studentinfo: true
monofont: 'Source Code Pro'
monofontoptions: 
  - Scale=0.55
---


   #. Erosión en morfología
   Contexto: Un patólogo necesita reducir el tamaño de pequeñas imperfecciones en una imagen digital de tejido tomada con microscopía.
   Pregunta: ¿Qué operación morfológica sería más adecuada para reducir las imperfecciones?
      #. Erosión.
      #. Dilatación.
      #. Transformada de Hough.
      #. Histograma igualado.


   #.  Histograma y contraste
   Contexto: Un técnico de imágenes médicas observa que una imagen de ultrasonido muestra un bajo contraste entre los tejidos debido a una mala distribución de los niveles de intensidad.
   Pregunta: ¿Qué herramienta de procesamiento de imágenes es la más adecuada para mejorar el contraste en esta situación?
      #. Ecualización de histograma.
      #. Filtro de mediana.
      #. Filtro Laplaciano.
      #. Umbralización global.

   #. Aplicación de la convolución
   Contexto: En una imagen de resonancia magnética de una rodilla, se requiere un filtro que resalte las líneas y bordes de los huesos para evaluar posibles fracturas.
   Pregunta: ¿Qué operación de procesamiento de imágenes debe aplicarse a esta imagen?
      #. Convolución con un filtro de Sobel.
      #. Filtro de promedio.
      #. Ecualización de histograma.
      #. Transformada de Fourier.

   #. Un técnico en imágenes está procesando una imagen de rayos X que contiene ruido "sal y pimienta". ¿Qué filtro sería el más adecuado para reducir este tipo de ruido en la imagen?
      #. Filtro de mediana.
      #. Filtro de promedio.
      #. Convolución con filtro Laplaciano.
      #. Transformada de Fourier.

   #. Un radiólogo necesita comparar imágenes de tomografía computarizada tomadas en diferentes momentos para evaluar la progresión de un tumor cerebral. Sin embargo, las imágenes han sido capturadas con ángulos ligeramente diferentes. Para realizar una comparación precisa, el radiólogo decide rotar una de las imágenes, de manera que coincida con la otra sin distorsionar las proporciones originales del cerebro. ¿Qué tipo de transformación geométrica debe aplicar el radiólogo para rotar la imagen y mantener la coherencia de las proporciones?
         #. Transformación afín.
         #. Transformación de escala.
         #. Transformación bilineal.
         #. Transformación polar.

   #. Umbralización adaptativa
   Contexto: Un investigador está analizando imágenes de microscopía con variaciones de iluminación y necesita segmentar las células de manera precisa.
   Pregunta: ¿Qué técnica de umbralización es más adecuada para manejar las variaciones de iluminación en la imagen?
      #. Filtro de Sobel.
      #. Convolución.
      #. Umbralización adaptativa.
      #. Transformada de Fourier.

   #. Un radiólogo está trabajando con imágenes de mamografía para detectar posibles tumores. Desea separar las áreas de tejido sospechoso del fondo oscuro. ¿Qué técnica de umbralización debería usar para aislar las regiones más brillantes?
      #. Umbralización global.
      #. Filtro de mediana.
      #. Umbralización adaptativa.
      #. Filtrado de alta frecuencia.

   #. Un radiólogo está utilizando mamografías para identificar áreas sospechosas de tejido. Para segmentar automáticamente las regiones de interés, decide aplicar una técnica de umbralización que maximice la separación entre el fondo y las áreas sospechosas. ¿Qué técnica de umbralización es la más adecuada para dividir la imagen en dos clases optimizadas de píxeles (fondo y tejido sospechoso)?
      #. Umbralización global.
      #. Umbralización de Otsu.
      #. Umbralización adaptativa.
      #. Filtro de mediana.